language: go

# import path is required to be zdd
go_import_path: zdd

# 1.6 is minimal version
go:
  - 1.6
  - tip

sudo: required

services:
  - docker

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -qq
  - sudo apt-get -y install nginx glide

install:
  - glide install
  - mkdir -p /home/vagrant/conf.d
  - mkdir -p /home/vagrant/html

script:
  - go test $(go list ./... | grep -v /vendor/)
  - go build -o zdd
  - ./zdd deploy -c example.yml -v 1.10
  - ./zdd deploy -c example.yml -v 1.11
  - ./zdd rollback -c example.yml
  - docker ps -a
