language: go

# import path is required to be zdd
go_import_path: zdd

# 1.6 is minimal version
go:
  - 1.6
  - tip

sudo: required

services:
  - docker

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -qq
  - sudo apt-get -y install nginx glide

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - glide install
  - mkdir -p /home/vagrant/conf.d
  - mkdir -p /home/vagrant/html

script:
  - ${GOPATH}/bin/overalls -project=zdd -covermode=count -ignore=.git,ansible,vendor
  - go run ./main.go deploy -c example.yml -v 1.10
  - go run ./main.go -c example.yml -v 1.11
  - go run ./main.go rollback -c example.yml

after_success:
  - ${GOPATH}/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken ${COVERALLS_TOKEN}
