#
# Docker
#
- name: docker - install https support for apt
  apt:
    name: "apt-transport-https"
    state: "present"

- name: docker - add repository key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"

- name: docker - add repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: "yes"

- name: docker - install
  apt:
    name: "docker-engine"
    state: "present"
